<?php

const PRODUCTO = "PRODUCTO";
const PROD_ID = "PROD_ID";
const PROD_NOMBRE = "PROD_NOMBRE";
const PROD_DESCRIPCION = "PROD_DESCRIPCION";
const PROD_PRECIO = "PROD_PRECIO";
const PROD_MODIFICACION = "PROD_MODIFICACION";
const PROD_ELIMINADO = "PROD_ELIMINADO";
